apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ddns-binding
  namespace: ddns
subjects:
  - kind: ServiceAccount
    name: ddns-sa  # Replace with your SA
    namespace: ddns         # SA must be in same namespace
roleRef:
  kind: ClusterRole
  name: ddns-role
  apiGroup: rbac.authorization.k8s.io
