apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ddns-role
  namespace: ddns
rules:
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get", "update", "patch"]
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "patch"]
  - apiGroups: ["traefik.io"]
    resources: ["middlewares"]
    verbs: ["*"]
