apiVersion: batch/v1
kind: CronJob
metadata:
  name: traefik-whitelist-sync
spec:
  schedule: "*/5 * * * *"
  successfulJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: traefik
          containers:
            - name: traefik-whitelist-sync
              image: kubitodev/traefik-ip-whitelist-sync:latest
              env:
                - name: WHITELIST_MIDDLEWARE_NAME
                  value: ip-whitelist
                - name: WHITELIST_TRAEFIK_NAMESPACE
                  value: traefik-system
                # - name: WHITELIST_CUSTOM_DOMAIN
                #   value: example.com
          restartPolicy: OnFailure
