apiVersion: batch/v1
kind: CronJob
metadata:
  name: ddns-cronjob
  namespace: ddns
spec:
  schedule: "*/5 * * * *"
  successfulJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: ddns-sa
          containers:
            - name: ddns-sync
              image: intrickster/ddns:0.0.1-snapshot
              # imagePullPolicy: Always #debug
              imagePullPolicy: IfNotPresent
              env:
                - name: DOMAIN
                  value: "{REPALCE_ME}"
                - name: RESOURCES_TO_PATCH
                  value: "traefik_middleware,cluster_config_map,porkbun_dns"
                - name: WHITELIST_MIDDLEWARE_NAME
                  value: "{REPALCE_ME}"
                - name: WHITELIST_TRAEFIK_NAMESPACE
                  value: "{REPALCE_ME}"
                - name: PORKBUN_API_KEY
                  valueFrom:
                    secretKeyRef:
                      name: porkbun-api-keys
                      key: PORKBUN_API_KEY
                - name: PORKBUN_SECRET_KEY
                  valueFrom:
                    secretKeyRef:
                      name: porkbun-api-keys
                      key: PORKBUN_SECRET_API_KEY
                - name: TTL
                  value: "300"
                - name: SUBDOMAIN
                  value: "{REPALCE_ME}"
                - name: CONFIG_MAPS_TO_UPDATE
                  value: |
                    [
                      {
                        "name": "config_map_name_1",
                        "namespace": "namespace_1",
                        "key": "key_name_1",
                      },
                      {
                        "name": "config_map_name_2",
                        "namespace": "namespace_2",
                        "key": "key_name_2",
                      }
                    ]
                - name: DEPLOYMENTS_TO_RESTART
                  value: |
                    [
                      {
                        "name": "deployment_name_1",
                        "namespace": "namespace_1"
                      },
                      {
                        "name": "deployment_name_2",
                        "namespace": "namespace_2"
                      }
                    ]
          restartPolicy: OnFailure