kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: patch-middleware
subjects:
- kind: ServiceAccount
  name: traefik
roleRef:
  kind: Role
  name: patch-middleware
  apiGroup: rbac.authorization.k8s.io
