kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: patch-traefik-middleware-rolebinding
  namespace: traefik
subjects:
- kind: ServiceAccount
  name: patch-traefik-middleware-sa
  namespace: traefik
roleRef:
  kind: Role
  name: patch-traefik-middleware-role
  apiGroup: rbac.authorization.k8s.io